CREATE DEFINER=`dba`@`%` FUNCTION `MSG_TEXTO`(P_TEXTO_IDENTIFICADOR VARCHAR(30)) RETURNS varchar(2000) CHARSET latin1
BEGIN

DECLARE   V_TEXTO    VARCHAR(2000);
DECLARE   V_ID_TEXTO INT;

    
     -- PROCURA O TEXTO PADRÃO
     SELECT T.TEX_MENSAGEM, T.ID_TEXTO
	   INTO V_TEXTO , V_ID_TEXTO 
       FROM TEXTO T
	  WHERE  T.TEX_IDENTIFICADOR = P_TEXTO_IDENTIFICADOR;

RETURN V_TEXTO;

END