CREATE DEFINER=`dba`@`%` PROCEDURE `ALTERAR_PLAYLIST`(IN  P_ID_PLAYLIST INT,
													  IN  P_ID_USUARIO  INT,
                                                      IN  P_PLA_NOME    VARCHAR(255),
													  IN  P_COMMIT      CHAR(1),
													  OUT P_OK 	        CHAR(1),
													  OUT P_RETORNO     VARCHAR(2000))
BEGIN

DECLARE V_TEXTO VARCHAR(2000);
 
CALL VALIDA_CAMPO_OBRIGATORIO(P_PLA_NOME, 'PLAYLIST', 'PLA_NOME');

CALL VALIDA_LOOKUP(P_ID_PLAYLIST, 'PLAYLIST', 'ID_PLAYLIST');

CALL VALIDA_LOOKUP(P_ID_USUARIO, 'USUARIO', 'ID_USUARIO');

   
   -- VALIDA SE PLAYLIST PERTENCE AO MESMO USUÁRIO
   SELECT COUNT(1)
	    INTO @V_COUNT
     FROM PLAYLIST P
	WHERE P.ID_USUARIO   = P_ID_USUARIO
	  AND P.ID_PLAYLIST = P_ID_PLAYLIST;
      
 IF @V_COUNT = 0 THEN
    CALL MSG_ERRO('PLAYLIST_NAO_PERTENCE_USUARIO', P_PLA_NOME, NULL, NULL, NULL, NULL);
	      -- A playlist :param1 não pertence ao seu usuário.
 END IF;

   -- VALIDA SE USUÁRIO JÁ POSSUI A MESMA PLAYLIST
   SELECT COUNT(1)
	    INTO @V_COUNT
     FROM PLAYLIST P
	WHERE P.ID_USUARIO = P_ID_USUARIO
	  AND UPPER(TRIM(P.PLA_NOME)) = UPPER(TRIM(P_PLA_NOME));

 IF @V_COUNT > 0 THEN
    CALL MSG_ERRO('PLAYLIST_USUARIO_EXISTE', P_PLA_NOME, NULL, NULL, NULL, NULL);
	      -- Você já possui a playlist :param1.
 END IF;
  
   -- ATUALIZA PLAYLIST
   UPDATE PLAYLIST P
	  SET P.PLA_NOME =  P_PLA_NOME
	WHERE P.ID_PLAYLIST = P_ID_PLAYLIST;

SET V_TEXTO :=  MSG_SUCESSO('ALTERAR_PLAYLIST', P_PLA_NOME, NULL, NULL, NULL, NULL);  
				-- A playlist :param1 foi alterada com sucesso.

SET P_OK      := 'S';
SET P_RETORNO := V_TEXTO;

IF IFNULL(P_COMMIT, 'N') = 'S'THEN
 COMMIT;
END IF;

END