CREATE DEFINER=`dba`@`%` PROCEDURE `ALTERAR_ARTISTA`(IN  P_ID_ARTISTA    INT,
													 IN  P_ART_NOME      VARCHAR(255),
													 IN  P_ART_LINK_FOTO VARCHAR(500),
													 IN  P_COMMIT        CHAR(1),
													 OUT P_OK 	         CHAR(1),
													 OUT P_RETORNO       VARCHAR(2000))
BEGIN

DECLARE V_TEXTO	        VARCHAR(2000);
DECLARE V_ID_ARTISTA    INT;
DECLARE V_ART_NOME      VARCHAR(255);
DECLARE V_ART_LINK_FOTO VARCHAR(500);

CALL VALIDA_CAMPO_OBRIGATORIO(P_ART_NOME, 'ARTISTA', 'ART_NOME');

CALL VALIDA_LOOKUP(P_ID_ARTISTA, 'ARTISTA', 'ID_ARTISTA');
-- DADOS DO ARTISTA
SELECT A.ART_NOME, A.ART_LINK_FOTO
	 INTO V_ART_NOME, V_ART_LINK_FOTO
     FROM ARTISTA A
		WHERE A.ID_ARTISTA = P_ID_ARTISTA;
        
	
-- VERIFICA SE ARTISTA DE MESMO NOME JÁ EXISTE    
SELECT A.ID_ARTISTA
	 INTO V_ID_ARTISTA
     FROM ARTISTA A
		WHERE UPPER(TRIM(A.ART_NOME)) = UPPER(TRIM(P_ART_NOME));

  IF V_ID_ARTISTA IS NOT NULL AND V_ID_ARTISTA != P_ID_ARTISTA THEN
  CALL MSG_ERRO('ARTISTA_EXISTE', P_ART_NOME, NULL, NULL, NULL, NULL);
  -- O artista :param1 já existe.
  END IF;
  
-- ATUALIZA ARTISTA
UPDATE ARTISTA
	SET ART_NOME      = IFNULL(P_ART_NOME,V_ART_NOME),
        ART_LINK_FOTO = IFNULL(P_ART_LINK_FOTO,V_ART_LINK_FOTO)
  WHERE ID_ARTISTA    = P_ID_ARTISTA;

SET V_TEXTO :=  MSG_SUCESSO('ALTERAR_ARTISTA', P_ART_NOME, NULL,NULL,NULL,NULL); 
				-- O artista :param1 foi alterado com sucesso.

SET P_OK      := 'S';
SET P_RETORNO := V_TEXTO;

IF IFNULL(P_COMMIT,'N') = 'S'THEN
 COMMIT;
END IF;

END