CREATE DEFINER=`dba`@`%` PROCEDURE `ALTERAR_PLAYLIST`(IN  P_ID_PLAYLIST INT,
													  IN  P_ID_USUARIO  INT,
                                                      IN  P_PLA_NOME    VARCHAR(255),
													  IN  P_COMMIT      CHAR(1),
													  OUT P_OK 	        CHAR(1),
													  OUT P_RETORNO     VARCHAR(2000))
ALTERAR_PLAYLIST:BEGIN
 
CALL VALIDA_CAMPO_OBRIGATORIO(P_PLA_NOME, 'PLAYLIST', 'PLA_NOME', P_OK, P_RETORNO);

     IF P_OK = 'N' THEN
        LEAVE ALTERAR_PLAYLIST;
     END IF;
     
CALL VALIDA_LOOKUP(P_ID_PLAYLIST, 'PLAYLIST', 'ID_PLAYLIST', P_OK, P_RETORNO);

     IF P_OK = 'N' THEN
        LEAVE ALTERAR_PLAYLIST;
     END IF;

CALL VALIDA_USUARIO(P_ID_USUARIO, 'USUARIO', P_OK, P_RETORNO);

     IF P_OK = 'N' THEN
        LEAVE ALTERAR_PLAYLIST;
     END IF;

   
   -- VALIDA SE PLAYLIST PERTENCE AO MESMO USUÁRIO
   SELECT COUNT(1)
	    INTO @V_COUNT
     FROM PLAYLIST P
	WHERE P.ID_USUARIO   = P_ID_USUARIO
	  AND P.ID_PLAYLIST = P_ID_PLAYLIST;
      
 IF @V_COUNT = 0 THEN
    CALL MSG_ERRO('PLAYLIST_NAO_PERTENCE_USUARIO', P_PLA_NOME, NULL, NULL, NULL, NULL, P_OK, P_RETORNO);
	      -- A playlist :param1 não pertence ao seu usuário.
          
        LEAVE ALTERAR_PLAYLIST;
        
 END IF;

   -- VALIDA SE USUÁRIO JÁ POSSUI A MESMA PLAYLIST
   SELECT COUNT(1)
	    INTO @V_COUNT
     FROM PLAYLIST P
	WHERE P.ID_USUARIO = P_ID_USUARIO
	  AND UPPER(TRIM(P.PLA_NOME)) = UPPER(TRIM(P_PLA_NOME));

 IF @V_COUNT > 0 THEN
    CALL MSG_ERRO('PLAYLIST_USUARIO_EXISTE', P_PLA_NOME, NULL, NULL, NULL, NULL, P_OK, P_RETORNO);
	      -- Você já possui a playlist :param1.
          
          LEAVE ALTERAR_PLAYLIST;
          
 END IF;
  
   -- ATUALIZA PLAYLIST
   UPDATE PLAYLIST P
	  SET P.PLA_NOME =  P_PLA_NOME
	WHERE P.ID_PLAYLIST = P_ID_PLAYLIST;

CALL MSG_SUCESSO('ALTERAR_PLAYLIST', P_PLA_NOME, NULL, NULL, NULL, NULL, P_OK, P_RETORNO);  
							 -- A playlist :param1 foi alterada com sucesso.

      IF P_OK = 'N' THEN
         LEAVE ALTERAR_PLAYLIST;
      END IF;

IF IFNULL(P_COMMIT, 'N') = 'S'THEN
 COMMIT;
END IF;

END