CREATE DEFINER=`dba`@`%` PROCEDURE `ALTERAR_USUARIO`(IN  P_ID_USUARIO     INT,
													 IN  P_USU_EMAIL      VARCHAR(255),
													 IN  P_USU_SENHA      VARCHAR(255),
                                                     IN  P_USU_ATIVO 	  INT,
													 IN  P_COMMIT         VARCHAR(1),
													 OUT P_OK 	          VARCHAR(1),
													 OUT P_RETORNO        VARCHAR(2000))
ALTERAR_USUARIO:BEGIN

DECLARE V_ID_USUARIO INT;
DECLARE V_USU_EMAIL VARCHAR(255);

CALL VALIDA_CAMPO_OBRIGATORIO(P_USU_EMAIL, 'USUARIO', 'USU_EMAIL', P_OK, P_RETORNO);

	IF P_OK = 'N' THEN
       LEAVE ALTERAR_USUARIO;
    END IF;
    
CALL VALIDA_CAMPO_OBRIGATORIO(P_USU_SENHA, 'USUARIO', 'USU_SENHA', P_OK, P_RETORNO);

	IF P_OK = 'N' THEN
       LEAVE ALTERAR_USUARIO;
    END IF;
 
CALL VALIDA_USUARIO(P_ID_USUARIO, 'USUARIO', P_OK, P_RETORNO);

    IF P_OK = 'N' THEN
       LEAVE ALTERAR_USUARIO;
    END IF;
 
  -- DADOS DO USUARIO
  SELECT U.USU_EMAIL 
	 INTO V_USU_EMAIL 
        FROM  USUARIO U 
      WHERE U.ID_USUARIO = P_ID_USUARIO;

IF V_USU_EMAIL != P_USU_EMAIL THEN

     -- VERIFICA SE EMAIL JA EXISTE PARA OUTRO USUARIO
     SELECT COUNT(1)
	 INTO @V_COUNT FROM USUARIO U
		WHERE U.USU_EMAIL = P_USU_EMAIL;
        
  IF @V_COUNT > 0 THEN 
   CALL MSG_ERRO('EMAIL_EXISTE', P_USU_EMAIL, NULL, NULL, NULL, NULL, P_OK, P_RETORNO);
		          -- O e-mail :param1 já existe.
   
       LEAVE ALTERAR_USUARIO;
    
  END IF;

END IF;

    -- ALTERAR USUARIO
    UPDATE USUARIO U 
	   SET U.USU_EMAIL      = P_USU_EMAIL,
           U.USU_ATIVO      = P_USU_ATIVO
     WHERE U.ID_USUARIO     = P_ID_USUARIO;

     CALL MSG_SUCESSO('ALTERAR_USUARIO', NULL, NULL,NULL,NULL,NULL, P_OK, P_RETORNO); 
					 -- Usuário alterado com sucesso.
     
          IF P_OK = 'N' THEN
             LEAVE ALTERAR_USUARIO; 
          END IF;

IF IFNULL(P_COMMIT,'N') = 'S'THEN
 COMMIT;
END IF;

END