CREATE DEFINER=`dba`@`%` PROCEDURE `INCLUIR_USUARIO`(OUT P_ID_USUARIO INT,
													 IN  P_USU_EMAIL  VARCHAR(255),
													 IN  P_USU_SENHA  VARCHAR(255),
													 IN  P_COMMIT     VARCHAR(1),
													 OUT P_OK 	      VARCHAR(1),
													 OUT P_RETORNO    VARCHAR(2000))
INCLUIR_USUARIO:BEGIN

DECLARE V_TEXTO	VARCHAR(2000);

CALL VALIDA_CAMPO_OBRIGATORIO(P_USU_EMAIL, 'USUARIO', 'USU_EMAIL', P_OK, P_RETORNO);

	 IF P_OK = 'N' THEN
        LEAVE INCLUIR_USUARIO;
     END IF;
     
CALL VALIDA_CAMPO_OBRIGATORIO(P_USU_SENHA, 'USUARIO', 'USU_SENHA', P_OK, P_RETORNO);

	 IF P_OK = 'N' THEN
        LEAVE INCLUIR_USUARIO;
     END IF;

     SELECT COUNT(1)
	 INTO @V_COUNT FROM USUARIO U
		WHERE U.USU_EMAIL = P_USU_EMAIL;
        
  IF @V_COUNT > 0 THEN 
     CALL MSG_ERRO('EMAIL_EXISTE', P_USU_EMAIL, NULL, NULL, NULL, NULL, P_OK, P_RETORNO);
     -- O e-mail :param1 já existe.
		
        LEAVE INCLUIR_USUARIO;
     
  END IF;

-- incluir usuário
INSERT INTO USUARIO (USU_EMAIL, USU_SENHA)
	VALUES(P_USU_EMAIL, MD5(P_USU_SENHA));


CALL MSG_SUCESSO('INCLUIR_USUARIO', NULL, NULL, NULL, NULL, NULL, P_OK, P_RETORNO);
                -- Usuário cadastrado com sucesso.

	 IF P_OK = 'N' THEN
        LEAVE INCLUIR_USUARIO;
     END IF;

IF IFNULL(P_COMMIT,'N') = 'S'THEN
 COMMIT;
END IF;

-- retorna o id do usuário cadastrado
SET P_ID_USUARIO := LAST_INSERT_ID();


END