CREATE DEFINER=`dba`@`%` PROCEDURE `MSG_ERRO`(IN P_TEX_IDENTIFICADOR VARCHAR(30),
							IN P_PARAM1            VARCHAR(100),
							IN P_PARAM2            VARCHAR(100),
							IN P_PARAM3            VARCHAR(100),
							IN P_PARAM4            VARCHAR(100),
							IN P_PARAM5            VARCHAR(100))
BEGIN

DECLARE V_MSGERRO         VARCHAR(2000);

 -- PEGA A MSG DE ERRO    
      SET V_MSGERRO = MSG_TEXTO(P_TEX_IDENTIFICADOR);
    
      -- SUBSTITUI OS PARÂMETROS
      IF P_PARAM1 IS NOT NULL THEN
       SET V_MSGERRO = REPLACE(V_MSGERRO, ':param1', P_PARAM1);
      END IF;
      IF P_PARAM2 IS NOT NULL THEN
       SET V_MSGERRO = REPLACE(V_MSGERRO, ':param2', P_PARAM2);
      END IF;
      IF P_PARAM3 IS NOT NULL THEN
       SET V_MSGERRO = REPLACE(V_MSGERRO, ':param3', P_PARAM3);
      END IF;
      IF P_PARAM4 IS NOT NULL THEN
       SET V_MSGERRO = REPLACE(V_MSGERRO, ':param4', P_PARAM4);
      END IF;
      IF P_PARAM5 IS NOT NULL THEN
       SET V_MSGERRO = REPLACE(V_MSGERRO, ':param5', P_PARAM5);
      END IF;
	
    
    IF V_MSGERRO IS NULL THEN
      SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'ERRO ! MENSAGEM NAO CADASTRADA', MYSQL_ERRNO = 1001;
    ELSE
	  SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = V_MSGERRO, MYSQL_ERRNO = 1001;
    END IF;
  
END