CREATE DEFINER=`dba`@`%` PROCEDURE `REGERAR_SENHA_USUARIO`(IN  P_ID_USUARIO INT,
										                   OUT P_SENHA      VARCHAR(255),
                                                           IN  P_COMMIT	    VARCHAR(1),
                                                           OUT P_OK	        VARCHAR(1),
                                                           OUT P_RETORNO    VARCHAR(2000))
BEGIN

DECLARE V_TEXTO	     VARCHAR(2000);
DECLARE V_USU_EMAIL  VARCHAR(255);
DECLARE V_SENHA	     VARCHAR(255);
DECLARE V_QTD_STRING INT;
DECLARE V_POSICAO	 INT;

CALL VALIDA_USUARIO(P_ID_USUARIO, 'USUARIO');
        
 SET P_SENHA = NULL;
 -- DEFINE SENHA COM NOME DO EMAIL MAIS NUMERO ALEATORIO DE 1 a 999
   SELECT  CONCAT(REMOVE_ACENTOS(LOWER(SUBSTRING_INDEX(SUBSTRING_INDEX(U.USU_EMAIL, '@', 1), '@', -1))),
		   FLOOR(1+RAND()*999))
	  INTO V_USU_EMAIL
    FROM USUARIO U
      WHERE U.ID_USUARIO = P_ID_USUARIO;
    
   -- EMBARALHA A SENHA DEFINIDA COM NOME DO USUARIO MAIS NUMERO ALEATORIO 
   SET V_QTD_STRING = LENGTH(V_USU_EMAIL);
    WHILE V_QTD_STRING > 0
    DO
      SET V_POSICAO = 1 + FLOOR(RAND() * V_QTD_STRING);
      SET V_SENHA = CONCAT(IFNULL(V_SENHA,''), MID(V_USU_EMAIL, V_POSICAO, 1));
      SET V_USU_EMAIL = CONCAT(LEFT(V_USU_EMAIL, V_POSICAO - 1), MID(V_USU_EMAIL, V_POSICAO + 1, V_QTD_STRING));
      SET V_QTD_STRING = V_QTD_STRING - 1;
    END WHILE;

      -- ATUALIZA A NOVA SENHA DO USUÁRIO
	  UPDATE USUARIO U
		 SET U.USU_SENHA  = V_SENHA
	   WHERE U.ID_USUARIO = P_ID_USUARIO;
 
 SET V_TEXTO :=  MSG_TEXTO('REGERAR_SENHA_USUARIO'); 
			     -- Senha alterada com sucesso.
                
 -- RETORNA A NOVA SENHA
SET P_SENHA = V_SENHA;
SET P_OK      := 'S';
SET P_RETORNO := V_TEXTO;
 
 IF IFNULL(P_COMMIT,'N') = 'S'THEN
 COMMIT;
END IF;
 

END