CREATE DEFINER=`dba`@`%` PROCEDURE `VALIDA_USUARIO`(IN  P_ID_USUARIO INT,
													IN  P_TABELA     VARCHAR(30),
													OUT P_OK	     CHAR(1),
                                                    OUT P_RETORNO    VARCHAR(2000))
VALIDA_USUARIO:BEGIN  
 
 CALL VALIDA_CAMPO_OBRIGATORIO(P_ID_USUARIO, P_TABELA, 'ID_USUARIO', P_OK, P_RETORNO);
  
   IF P_OK = 'N' THEN
	LEAVE VALIDA_USUARIO;
   END IF;
 
 
 CALL VALIDA_LOOKUP(P_ID_USUARIO, P_TABELA, 'ID_USUARIO', P_OK, P_RETORNO);
 
   IF P_OK = 'N' THEN
	LEAVE VALIDA_USUARIO;
   END IF;
 
 CALL MSG_SUCESSO('SUCESSO_VALIDA_USUARIO', P_ID_USUARIO, NULL, NULL, NULL, NULL, P_OK, P_RETORNO);
 
END